### ISSUE TITLE
Faktory::Testing.fake! is still attempting to hit localhost....

### ISSUE THREAD

**Issue by rwilliams3088** [contribsys/faktory_worker_ruby#75] opened 2023-03-30 21:23 UTC
I've added a line of code that calls perform_async on a job as part of an after_commit handler on one of my Active Record models, and now a bunch of unit tests are failing. I have attempted (in many locations) to call Faktory::Testing.fake!, yet it is still attempting to hit a faktory server rather than just mock things locally.

How can I properly mock Faktory for the purposes of unit testing (not integration testing)

**Comment by mperham** [comment] 2023-03-30 23:38
It looks like you have a test fixture factory which is creating a Faktory job.

     # ./app/models/store.rb:35:in `update_batch_priority!'
     # ./spec/api/api/printer_validation_spec.rb:15:in `block (3 levels) in <top (required)>'

**Comment by rwilliams3088** [comment] 2023-03-31 17:23
The store model is setup to kick off a job using `perform_async` whenever a particular attribute on the model is modified on the after_commit hook. It's not a test fixture.

**Comment by rwilliams3088** [comment] 2023-03-31 18:01
Well I did tell you that in the OP

**Comment by rwilliams3088** [comment] 2023-03-31 18:02
I talked with one of my coworkers who ran into similar errors in one of our other projects. It turns out there is a bug in version 1.1.2 of faktory_worker_ruby. Reverting to 1.1.1 fixes it.

**Comment by mperham** [comment] 2023-03-31 18:04
Have you tried upgrading?

**Comment by rwilliams3088** [comment] 2023-03-31 18:07
v1.2.0 is the latest

**Comment by mperham** [comment] 2023-03-31 18:34
Sorry I misread and thought you said 1.1.2.

**Comment by mperham** [comment] 2023-03-31 21:53
It took me too long to realize that this is a dupe of #74. v1.3.0 is now available with the fix.

**Closed by mperham** 2023-03-31 21:53 UTC
